name: game_loop
version: 0.9.4
author: John McCutchan <john@johnmccutchan.com>
description: The Game Loop for Dart
homepage: https://github.com/johnmccutchan/game_loop
dev_dependencies:
  browser: any
  unittest: any
